#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# home:
#    path: /
#    controller: App\Controller\HomeController::index

# user_connect:
#    path: /User
#    controller: App\Controller\HomeController::index

logout:
   path: /logout
